In [1]:
import torch

In [ ]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x, y):
        self.x = x # apple
        self.y = y # apple_num
        out = x * y
        return out
    
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x
        return dx, dy

In [ ]:
apple = 100
apple_num = 2
tax = 1.1

mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

# forward propagation
apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)

In [ ]:
# back propagation
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print("dapple:{} , dapple_num:{} , dtax : {}".format(dapple, dapple_num, dtax))

# mask 사용방법

In [ ]:
x = torch.FloatTensor([0,-1,0,3,-2,-1,5])
x


In [ ]:
mask = x <= 0
mask

In [ ]:
out = x
print(x)
out[mask] =0
out

# backward() 개념

In [44]:
x = torch.tensor([1.0,2.0,3.0], requires_grad = True)
y = x**3
cnt = 0
#while y.data.norm() <= 1000:
#    y = y*2
#    cnt+=1
print(x)
print(y)
#print(cnt)

tensor([1., 2., 3.], requires_grad=True)
tensor([ 1.,  8., 27.], grad_fn=<PowBackward0>)


In [45]:
v = torch.FloatTensor([0.1,1.0,0.0001]) # 미분 후 x원소 값 대입 후 (x:곱) v
z  = y.backward(v) # y의 연산 과정을 기억해둬서 미분 시 총 연산과정 식을 사용
# 이 연산 과정을 시킬 tensor의 경우 requires_grad = True로 설정해주며
# 부분적으로 이 과정을 기억시키지 않고 싶을때
# with torch.no_grad():   를 사용한다
    

print(z)
print(x.grad)

None
tensor([3.0000e-01, 1.2000e+01, 2.7000e-03])
