In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [4]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [5]:
w = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(w)+b)))

print(hypothesis)

hypothesis = torch.sigmoid(-(x_train.matmul(w)+b))

print(hyphothesis)
print(y_train)

loss = -(y_train*torch.log(hypothesis) + (1-y_train)*torch.log(1- hypothesis))
loss

cost = loss.mean()
cost

F.binary_cross_entropy(hypothesis, y_train)

In [6]:
import numpy as np

In [32]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
len(x_data[0])
y_train

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
      

In [8]:
class BC(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(8,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,x):
        return self.sigmoid(self.linear(x))


In [31]:
model = BC()
optimizer = optim.SGD(model.parameters(), lr=1)

epochs = 100
for epoch in range(epochs+1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_p = prediction.float() == y_train
        correct_rate = correct_p.sum().item() / len(correct_p)
        # print("{:.6f}, {:.2f}".format(cost.item(), correct_rate*100))
        # print(hypothesis, prediction)

0.772115, 34.91
tensor([[0.4325],
        [0.4199],
        [0.4204],
        [0.3615],
        [0.4720],
        [0.4114],
        [0.3681],
        [0.4446],
        [0.3549],
        [0.4388],
        [0.3990],
        [0.4324],
        [0.5063],
        [0.4371],
        [0.4450],
        [0.4134],
        [0.4352],
        [0.3086],
        [0.3473],
        [0.3776],
        [0.4554],
        [0.3865],
        [0.4698],
        [0.4265],
        [0.4030],
        [0.3904],
        [0.4689],
        [0.4152],
        [0.4540],
        [0.3766],
        [0.3918],
        [0.4471],
        [0.4968],
        [0.4214],
        [0.4612],
        [0.4921],
        [0.4056],
        [0.4129],
        [0.3190],
        [0.4324],
        [0.4910],
        [0.4365],
        [0.4050],
        [0.4771],
        [0.3608],
        [0.4507],
        [0.4521],
        [0.4296],
        [0.3906],
        [0.3664],
        [0.4003],
        [0.4149],
        [0.4183],
        [0.4471],
        [0.3

        [1]], dtype=torch.uint8)
0.486660, 77.47
tensor([[0.4350],
        [0.9106],
        [0.2642],
        [0.9223],
        [0.2410],
        [0.7384],
        [0.9223],
        [0.5897],
        [0.2723],
        [0.5173],
        [0.6870],
        [0.2100],
        [0.2961],
        [0.3273],
        [0.7235],
        [0.4722],
        [0.7125],
        [0.8239],
        [0.7993],
        [0.5988],
        [0.6462],
        [0.1351],
        [0.6608],
        [0.6662],
        [0.3764],
        [0.9253],
        [0.5599],
        [0.6303],
        [0.6908],
        [0.4766],
        [0.9411],
        [0.8486],
        [0.5977],
        [0.8143],
        [0.3915],
        [0.6460],
        [0.8070],
        [0.5481],
        [0.4816],
        [0.3944],
        [0.8194],
        [0.1976],
        [0.4178],
        [0.1006],
        [0.5823],
        [0.9214],
        [0.7063],
        [0.7013],
        [0.9288],
        [0.9205],
        [0.9160],
        [0.2651],
        [0.3838