In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim



In [2]:
x_train = torch.FloatTensor([[1, 2, 1],
                             [1, 3, 2],
                             [1, 3, 4],
                             [1, 5, 5],
                             [1, 7, 5],
                             [1, 2, 5],
                             [1, 6, 6],
                             [1, 7, 7]
                            ])
y_train = torch.LongTensor([2, 2, 2, 1, 1, 1, 0, 0])


In [136]:
x_test = torch.FloatTensor([[1, 6, 5], [1, 5, 2], [3, 3, 4]])
y_test = torch.LongTensor([1,2,2])

In [162]:
class SMCM(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,3)
        
    def forward(self, x):
        # return F.log_softmax(self.linear(x), dim =1)
        return self.linear(x)


In [163]:
model = SMCM()

In [164]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [165]:
def training(model, optimizer, x_train, y_train):
    
    epochs = 100
    
    for epoch in range(epochs+1):
        prediction = model(x_train)
        cost = F.cross_entropy(prediction, y_train)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        if epoch % 25 ==0:
            print("cost:{:.6f}".format(cost))
            print(prediction)

    

In [166]:
def test(model, x_test, y_test):
    prediction = model(x_test)
    predicted_classes = prediction.max(1)[1]
    correct_count = (predicted_classes == y_test).sum().item()
    cost = F.cross_entropy(prediction, y_test)
    
    print(prediction.max(1))
    print(prediction)
    print(predicted_classes)
    print(y_test)
    print(predicted_classes == y_test)
    print("ac:{}, cost:{}".format((correct_count/len(y_test)), cost))
    

In [167]:
training(model, optimizer, x_train, y_train)

cost:1.276198
tensor([[1.0513, 0.4958, 0.7894],
        [1.9792, 1.1053, 1.1049],
        [3.0116, 1.9172, 2.2493],
        [4.3512, 2.7302, 2.3081],
        [5.1745, 3.1374, 1.7947],
        [3.1162, 2.1195, 3.0782],
        [5.2791, 3.3397, 2.6236],
        [6.2070, 3.9493, 2.9391]], grad_fn=<AddmmBackward>)
cost:0.830989
tensor([[0.3120, 0.5317, 1.4927],
        [1.1174, 1.2915, 1.7805],
        [2.1835, 2.5687, 2.4259],
        [3.2613, 3.4496, 2.6786],
        [3.8060, 3.6919, 2.6086],
        [2.4442, 3.0861, 2.7836],
        [4.0667, 4.2094, 2.9663],
        [4.8721, 4.9691, 3.2540]], grad_fn=<AddmmBackward>)
cost:0.754481
tensor([[0.0203, 0.4391, 1.8770],
        [0.9017, 1.2099, 2.0777],
        [2.1415, 2.6211, 2.4154],
        [3.2844, 3.4571, 2.6480],
        [3.8073, 3.5876, 2.7118],
        [2.5000, 3.2615, 2.5524],
        [4.1657, 4.2280, 2.8487],
        [5.0471, 4.9988, 3.0494]], grad_fn=<AddmmBackward>)
cost:0.706550
tensor([[-0.2283,  0.4037,  2.1610],
        [ 0.7

In [168]:
test(model, x_test, y_test)

torch.return_types.max(
values=tensor([3.5668, 2.5577, 4.3637], grad_fn=<MaxBackward0>),
indices=tensor([1, 2, 2]))
tensor([[3.5467, 3.5668, 2.6345],
        [1.0627, 1.2861, 2.5577],
        [0.4419, 2.4672, 4.3637]], grad_fn=<AddmmBackward>)
tensor([1, 2, 2])
tensor([1, 2, 2])
tensor([1, 1, 1], dtype=torch.uint8)
ac:1.0, cost:0.476633220911026


# linear function test

a = torch.FloatTensor([1,3,5,6,7])
a

model2 = SMCM()

model2(a)