In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
z = torch.rand(3,5, requires_grad = True)
y = torch.randint(5,(3,)).long()
hypothesis = F.softmax(z, dim = 1)
print(z)
print("hypo:",hypothesis)
print(y)
print(y.unsqueeze(1))
hypothesis[0].sum()
y_one_hot = torch.zeros_like(hypothesis)

y_one_hot.scatter_(1,y.unsqueeze(1), 1)
#y_one_hot

tensor([[0.0327, 0.7439, 0.8333, 0.9000, 0.7648],
        [0.4651, 0.2914, 0.1750, 0.7335, 0.7296],
        [0.2393, 0.8320, 0.7943, 0.5977, 0.8802]], requires_grad=True)
hypo: tensor([[0.1028, 0.2094, 0.2290, 0.2448, 0.2139],
        [0.1923, 0.1617, 0.1439, 0.2515, 0.2506],
        [0.1269, 0.2295, 0.2211, 0.1816, 0.2409]], grad_fn=<SoftmaxBackward>)
tensor([1, 3, 2])
tensor([[1],
        [3],
        [2]])


tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

In [3]:
print(y_one_hot*-torch.log(hypothesis))
print((y_one_hot*-torch.log(hypothesis)).sum(dim=1))
cost = (y_one_hot*-torch.log(hypothesis)).sum(dim=1).mean()

cost

tensor([[0.0000, 1.5633, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.3802, 0.0000],
        [0.0000, 0.0000, 1.5093, 0.0000, 0.0000]], grad_fn=<MulBackward0>)
tensor([1.5633, 1.3802, 1.5093], grad_fn=<SumBackward2>)


tensor(1.4843, grad_fn=<MeanBackward0>)

a = torch.FloatTensor([[1,2,1,2],[2,3,2,3],[3,4,3,4],[4,5,4,5],[5,6,5,6]])
b = torch.FloatTensor([[3],[4],[5],[6],[7]])

a.sum(dim = 1)

In [4]:
F.cross_entropy(z,y)

tensor(1.4843, grad_fn=<NllLossBackward>)

In [5]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [6]:
w = torch.zeros((4,3), requires_grad = True) # 행렬곱 열 값이 0,1,2 세 인덱스를 나타내야하기때문에
b = torch.zeros(1, requires_grad = True)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)

optimizer = optim.SGD([w,b], lr = 0.1)
epochs = 1000
for epoch in range(epochs+1):
    # print(x_train.matmul(w)+b)
    hypothesis = F.softmax(x_train.matmul(w)+b, dim=1)
    # print(hypothesis)
    y_one_hot = torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
    cost = (y_one_hot* -torch.log(F.softmax(hypothesis, dim=1))).sum(dim =1).mean()
    # cost = (y_one_hot* -torch.log(hypothesis)).sum(dim =1).mean()
    # 위에서 f.softmax를 왜 한번 더 썼을지? 확인해본결과 정수비가 아니여서
    # 그런지 거듭할 수 록 격차가 좁아진다
    # 그렇다면 코스트값도 상대적으로 작아질 것이며 결과적으로 변동이 디테일해진다
    # print(y_one_hot)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if(epoch % 100 == 0):
        print(cost.item())
    
    
    

optimizer = optim.SGD([w,b], lr = 0.1)
epochs = 1000
for epoch in range(epochs+1):
    hypothesis = x_train.matmul(w)+b
    cost = F.cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if(epoch % 100 == 0):
        print(cost.item())
    
    
    

In [7]:
class SMCM(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,3)
    def forward(self, x):
        return self.linear(x)
    
model = SMCM()

In [8]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)
epochs = 1000
for epoch in range(epochs+1):
    hypothesis = model(x_train)
    
    cost = F.cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if(epoch % 100 == 0):
        print(cost.item())
    
    
    

2.144866704940796
0.6243172883987427
0.5476441383361816
0.4947519302368164
0.45084822177886963
0.4113711714744568
0.37408697605133057
0.3375181257724762
0.30065640807151794
0.2644827365875244
0.24208296835422516
