In [4]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [58]:
import pandas as pd
import numpy as np

data2 = pd.read_excel('모델인풋데이터셋처리전DF2.xls')

data2.drop(columns='Unnamed: 0', inplace=True)
data2.dropna(inplace=True)
dataT = data2.T

dataT


1           2           3           4           5    \
날짜      2017.10.16  2017.10.17  2017.10.18  2017.10.19  2017.10.20   
외국인              1           1           1    0.998683    0.999012   
국내기사점수    0.820362    0.820362    0.924833     0.82618     0.82618   
cross            1           1           1           1           1   
comp             0           0           1           1           0   
comp2            2           1           3           4           2   

               6           7           8           9           10   ...  \
날짜      2017.10.23  2017.10.24  2017.10.25  2017.10.26  2017.10.27  ...   
외국인              1    0.998352    0.997362    0.998352           1  ...   
국내기사점수    0.967078    0.959195    0.783967    0.866844    0.866844  ...   
cross            1           1           1           1           1  ...   
comp             1           1           0           1           0  ...   
comp2            3           4           2           3           2  ...   

               453         454         455         456         457  \
날짜      2019.09.05  2019.09.06  2019.09.10  2019.09.11  2019.09.16   
외국인       0.994898    0.995361    0.995825    0.990723    0.988867   
국내기사점수           0           0           1           1           1   
cross            1           1           1           1           1   
comp             0           1           1           0           1   
comp2            1           3           4           2           3   

               458         459         460         461         462  
날짜      2019.09.17  2019.09.18  2019.09.19  2019.09.20  2019.09.23  
외국인       0.993506    0.996753    0.997681           1           1  
국내기사점수           1           0           0           0           0  
cross            1           1           1           1           1  
comp             1           0           0           1           0  
comp2            4           2           1           3           2  

[6 rows x 462 columns]

In [59]:
#2차원배열 형태의 데이터셋 만들기

def createData(df, look_back = 1):
  dataX, dataY = [], []
  length = df.shape[1] 
  for i in range(length - look_back):
    dataX.append(dataT.iloc[1:5, i:i+look_back].to_numpy())
    dataY.append(dataT.iloc[5,i+look_back])

  X = np.asarray(dataX, dtype=np.float32)
  Y = np.asarray(dataY, dtype=np.float32)
  return X, Y

In [52]:
dataT.shape[1] 

#462의 길이

dataX, dataY = createData(dataT, 30)

#363 : 69 ( 8 : 2 비율로 train/test)

train_x = dataX[:362+1]
train_y = dataY[:362+1]
test_x = dataX[362+1:]
test_y = dataY[362+1:]
print(len(train_y))
print(len(test_x))
inf_row = 4
inf_col = 30

train_x

363
69


array([[[1.        , 1.        , 1.        , ..., 1.        ,
         1.        , 1.        ],
        [0.82036155, 0.82036155, 0.9248332 , ..., 0.8154493 ,
         0.8154493 , 0.8154493 ],
        [1.        , 1.        , 1.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 1.        , ..., 0.        ,
         1.        , 0.        ]],

       [[1.        , 1.        , 0.9986829 , ..., 1.        ,
         1.        , 1.        ],
        [0.82036155, 0.9248332 , 0.8261801 , ..., 0.8154493 ,
         0.8154493 , 0.8641133 ],
        [1.        , 1.        , 1.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 1.        , 1.        , ..., 1.        ,
         0.        , 1.        ]],

       [[1.        , 0.9986829 , 0.99901223, ..., 1.        ,
         1.        , 0.9989579 ],
        [0.9248332 , 0.8261801 , 0.8261801 , ..., 0.8154493 ,
         0.8641133 , 0.80039406],
        [1.        , 1.        , 1. 

In [60]:
train_y

array([3., 2., 3., 4., 2., 1., 3., 4., 2., 1., 3., 2., 3., 2., 3., 2., 3.,
       4., 4., 2., 3., 2., 1., 3., 2., 3., 2., 3., 4., 2., 1., 1., 1., 1.,
       3., 2., 3., 4., 2., 3., 2., 3., 4., 4., 2., 3., 4., 2., 3., 4., 2.,
       3., 2., 1., 3., 4., 4., 2., 3., 2., 3., 4., 4., 4., 2., 1., 3., 4.,
       4., 4., 2., 3., 4., 4., 2., 3., 2., 3., 2., 3., 4., 2., 3., 4., 2.,
       3., 2., 3., 2., 3., 2., 1., 1., 3., 4., 2., 1., 3., 2., 3., 2., 1.,
       3., 4., 4., 2., 3., 2., 3., 4., 2., 1., 3., 2., 1., 1., 3., 2., 3.,
       4., 4., 2., 3., 4., 2., 3., 4., 2., 3., 4., 2., 3., 2., 3., 2., 1.,
       3., 2., 1., 3., 2., 3., 2., 3., 4., 4., 2., 3., 4., 2., 3., 2., 1.,
       3., 2., 3., 2., 1., 1., 3., 4., 2., 1., 3., 2., 3., 2., 3., 4., 2.,
       1., 3., 2., 3., 2., 1., 3., 4., 2., 1., 1., 3., 4., 2., 3., 2., 3.,
       2., 3., 4., 2., 3., 2., 1., 1., 3., 4., 4., 2., 3., 4., 2., 1., 1.,
       3., 2., 3., 2., 3., 4., 4., 4., 4., 2., 1., 1., 3., 4., 2., 3., 2.,
       1., 3., 2., 1., 3.

In [53]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import sys
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers.convolutional import Conv1D,Conv2D, MaxPooling2D


In [54]:
x_train = train_x.reshape(train_x.shape[0], inf_row, inf_col, 1)
x_test = test_x.reshape(test_x.shape[0], inf_row, inf_col, 1)
y_train = train_y
y_test = test_y
len(y_train)
y_train

y_train = keras.utils.to_categorical(y_train, 5)
y_test = keras.utils.to_categorical(y_test, 5)

In [57]:
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [47]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), padding='same',
                 activation='relu',
                 input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(1, 1)))
model.add(Conv2D(64, (2, 2), activation='relu', padding='same'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(500, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(400, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(300, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(200, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(20, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax'))
model.summary()

# 현재 1위 69프로

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_17 (Conv2D)           (None, 4, 30, 32)         320       
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 3, 29, 32)         0         
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 3, 29, 64)         8256      
_________________________________________________________________
dropout_43 (Dropout)         (None, 3, 29, 64)         0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 5568)              0         
_________________________________________________________________
dense_43 (Dense)             (None, 500)               2784500   
_________________________________________________________________
dropout_44 (Dropout)         (None, 500)              

In [48]:
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['mae', 'mape','acc'])
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
hist = model.fit(x_train, y_train, batch_size=11, epochs=50,
                 verbose=1, 
                 validation_data=(x_test, y_test))



Train on 363 samples, validate on 69 samples
Epoch 1/50
363/363 [==============================] - 2s 6ms/step - loss: 1.6645 - accuracy: 0.2039 - val_loss: 1.5824 - val_accuracy: 0.3478
Epoch 2/50
363/363 [==============================] - 1s 4ms/step - loss: 1.5722 - accuracy: 0.2672 - val_loss: 1.5036 - val_accuracy: 0.3478
Epoch 3/50
363/363 [==============================] - 2s 4ms/step - loss: 1.5215 - accuracy: 0.3388 - val_loss: 1.4696 - val_accuracy: 0.3478
Epoch 4/50
363/363 [==============================] - 1s 4ms/step - loss: 1.5156 - accuracy: 0.3361 - val_loss: 1.4670 - val_accuracy: 0.3478
Epoch 5/50
363/363 [==============================] - 1s 4ms/step - loss: 1.4846 - accuracy: 0.3388 - val_loss: 1.4363 - val_accuracy: 0.3478
Epoch 6/50
363/363 [==============================] - 1s 4ms/step - loss: 1.4655 - accuracy: 0.3306 - val_loss: 1.4200 - val_accuracy: 0.3478
Epoch 7/50
363/363 [==============================] - 1s 4ms/step - loss: 1.4394 - accuracy: 0.3554 - v

In [49]:
score = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

69/69 [==============================] - 0s 268us/step
Test loss: 0.6837123684261156
Test accuracy: 0.6811594367027283
