In [1]:
import torch
import numpy as np

In [2]:
t = np.array([0,1,2,3,4,5,6,7])
t

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
print(t.ndim)
print(t.shape)



1
(8,)


In [4]:
t = np.array([[0,1,2],[2,3,4]])

In [5]:
print(t.ndim)
print(t.shape)

2
(2, 3)


In [6]:
t = torch.FloatTensor([[0,1,2], [1,2,3], [7,6,4]])
t

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [7., 6., 4.]])

In [18]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[2][:3])
print(t[1])
print(t[:2,:2])

2
torch.Size([3, 3])
torch.Size([3, 3])
tensor([7., 6., 4.])
tensor([1., 2., 3.])
tensor([[0., 1.],
        [1., 2.]])


In [25]:
t = torch.FloatTensor([[[0,1,3],[2,2,4]], [[1,0,5],[2,3,1]]])
t

tensor([[[0., 1., 3.],
         [2., 2., 4.]],

        [[1., 0., 5.],
         [2., 3., 1.]]])

In [33]:
print(t.dim())
print(t.shape)
print(t.size())
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))



3
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor(2.)
tensor([[0.5000, 0.5000, 4.0000],
        [2.0000, 2.5000, 2.5000]])
tensor([[1.0000, 1.5000, 3.5000],
        [1.5000, 1.5000, 3.0000]])
tensor([[1.3333, 2.6667],
        [2.0000, 2.0000]])


In [78]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -2))

tensor(24.)
tensor([[1., 1., 8.],
        [4., 5., 5.]])
tensor([[2., 3., 7.],
        [3., 3., 6.]])
tensor([[2., 3., 7.],
        [3., 3., 6.]])


In [41]:
t = torch.FloatTensor([[[0,1,3],[2,2,4]], [[1,0,5],[2,3,1]]])
t

tensor([[[0., 1., 3.],
         [2., 2., 4.]],

        [[1., 0., 5.],
         [2., 3., 1.]]])

In [52]:
torch.max(t, 2)

(tensor([[3., 4.],
         [5., 3.]]), tensor([[2, 2],
         [2, 1]]))

In [43]:
t.max()

tensor(5.)

In [53]:
t = torch.FloatTensor([[[0,1,3],[2,2,4]], [[1,0,5],[2,3,1]]])
t

tensor([[[0., 1., 3.],
         [2., 2., 4.]],

        [[1., 0., 5.],
         [2., 3., 1.]]])

In [72]:
print(t.view([4,1,3]))

tensor([[[0., 1., 3.]],

        [[2., 2., 4.]],

        [[1., 0., 5.]],

        [[2., 3., 1.]]])
