In [1]:
# PyTorch 라이브러리 임포트
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# scikit-learn 라이브러리 임포트
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

# Pandas 라이브러리 임포트
import pandas as pd



In [2]:
wine = load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [15]:
df1 = pd.DataFrame(wine.data, columns=wine.feature_names)
df2 = pd.DataFrame(wine.target)#, columns=wine.feature_names)

#excel_writer = pd.ExcelWriter('excel_output.xlsx', engine = 'xlsxwriter')
excel_writer2 = pd.ExcelWriter('excel_output_target.xlsx', engine = 'xlsxwriter')
#df1.to_excel(excel_writer)
df2.to_excel(excel_writer2)

#excel_writer.save()
excel_writer2.save()

In [4]:
wine_data = wine.data[0:130] # 130으로 제한한 이유는 라벨값이 0,1 로만 존재하기 위해서이다
wine_target = wine.target[0:130] # 아마 추측하기로는 crossentropyloss가 라벨값으로 원핫벡터값을 갖기 때문 같은데 모르겠다 ^^ !!


In [5]:
train_X, test_X, train_Y, test_Y = train_test_split(wine_data, wine_target, test_size = 0.2)
# 사이킷런에서 얻은 데이터셋을 train_test_split함수르 통해 트레인/테스트 용 설명/목적 변수를 8:2 비율로 나눈다

print(len(train_X))
print(len(test_X))
train_X

104
26


array([[1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
        3.420e+02],
       [1.164e+01, 2.060e+00, 2.460e+00, ..., 1.000e+00, 2.750e+00,
        6.800e+02],
       [1.229e+01, 1.610e+00, 2.210e+00, ..., 9.060e-01, 1.820e+00,
        8.700e+02],
       ...,
       [1.305e+01, 1.650e+00, 2.550e+00, ..., 1.120e+00, 2.510e+00,
        1.105e+03],
       [1.390e+01, 1.680e+00, 2.120e+00, ..., 9.100e-01, 3.330e+00,
        9.850e+02],
       [1.145e+01, 2.400e+00, 2.420e+00, ..., 8.000e-01, 3.390e+00,
        6.250e+02]])

In [6]:
train_X = torch.from_numpy(train_X).float() # 행렬화 실수니까~
train_Y = torch.from_numpy(train_Y).long() # 행렬화 정수니까~

test_X = torch.from_numpy(test_X).float()
test_Y = torch.from_numpy(test_Y).long()

print(train_X.shape)
print(train_Y.shape)
print(train_X)
print(train_Y)

torch.Size([104, 13])
torch.Size([104])
tensor([[  12.3700,    1.6300,    2.3000,  ...,    0.8900,    2.7800,
          342.0000],
        [  11.6400,    2.0600,    2.4600,  ...,    1.0000,    2.7500,
          680.0000],
        [  12.2900,    1.6100,    2.2100,  ...,    0.9060,    1.8200,
          870.0000],
        ...,
        [  13.0500,    1.6500,    2.5500,  ...,    1.1200,    2.5100,
         1105.0000],
        [  13.9000,    1.6800,    2.1200,  ...,    0.9100,    3.3300,
          985.0000],
        [  11.4500,    2.4000,    2.4200,  ...,    0.8000,    3.3900,
          625.0000]])
tensor([1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 1])


In [7]:
train = TensorDataset(train_X, train_Y) # torch.utils.data 내에 있는 함수로써 트레이닝 데이터 셋을 텐서화 시킨다


for i in train: # train내부에는 데이터셋 / 라벨값 으로 구성돼있음
    print(i)
    print("========")
# print(train[2])


train_loader = DataLoader(train, batch_size = 16, shuffle=True) 
# batch_size(epoch를 적정한 수로 나눈(iteration)중 회당 넣는 데이터셋 수)
# torch.utils.data 내에 있는 함수로써 말그대로 데이터 로더의 역할을 한다
# train
print(train_loader)

(tensor([ 12.3700,   1.6300,   2.3000,  24.5000,  88.0000,   2.2200,   2.4500,
          0.4000,   1.9000,   2.1200,   0.8900,   2.7800, 342.0000]), tensor(1))
(tensor([ 11.6400,   2.0600,   2.4600,  21.6000,  84.0000,   1.9500,   1.6900,
          0.4800,   1.3500,   2.8000,   1.0000,   2.7500, 680.0000]), tensor(1))
(tensor([ 12.2900,   1.6100,   2.2100,  20.4000, 103.0000,   1.1000,   1.0200,
          0.3700,   1.4600,   3.0500,   0.9060,   1.8200, 870.0000]), tensor(1))
(tensor([ 12.0000,   0.9200,   2.0000,  19.0000,  86.0000,   2.4200,   2.2600,
          0.3000,   1.4300,   2.5000,   1.3800,   3.1200, 278.0000]), tensor(1))
(tensor([  13.9400,    1.7300,    2.2700,   17.4000,  108.0000,    2.8800,
           3.5400,    0.3200,    2.0800,    8.9000,    1.1200,    3.1000,
        1260.0000]), tensor(0))
(tensor([  13.0700,    1.5000,    2.1000,   15.5000,   98.0000,    2.4000,
           2.6400,    0.2800,    1.3700,    3.7000,    1.1800,    2.6900,
        1020.0000]), tensor(0)

In [8]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__() # 상속받은 부모클래스의 init을 거친다
        self.fc1 = nn.Linear(13,96) 
        # (x,y | y = Ax + b) 선형변환을 거친다 -> 인풋 13종류 => 아웃풋 96 종류 // 따라서 이 부분이 입력층---중간층이다
        self.fc2 = nn.Linear(96,2)
        # 추후 이 변수는 fc1의 리턴값을 받기때문에 fc1의 y값 개수가 x값 개수와 동일하다 최종적으로 2개의 출력값을 내놓는다 // 중간층 ---출력층
    def forward(self, x): # 아직 이 함수가 어떻게 사용되어지는 모르겠지만 상속관계에서 호출되는 이유가 있는듯하다
        x = F.relu(self.fc1(x)) # torch.nn.functional의 ReLu는 활성화함수로써 입력값에 비례한 값으로 변환을 해준다
        x = self.fc2(x) # 위에서 얻은 값에 맞는 y값을 갖는다(fc2 직선 함수에서)
        return F.log_softmax(x, dim = 1) # 위에서 얻은 x값을 소프트맥스 함수를 통해 총합이 1이 되도록 비율에 맞춰 값을 변환한다
                                          # 정수배 개념이 아니다
    
    
model = Net()
          


In [9]:
criterion = nn.CrossEntropyLoss() # 손실함수를 지정한다 (분류문제에서는 crossentropy, 회귀문제에서는 mean_square_error를 사용)

optimizer = optim.SGD(model.parameters(), lr = 0.1) # 최적화 도구로 sgd -> 확률적 경사하강법이다 lr = learn rate
                                                    

for epoch in range(100): # 100번의 시행
    total_loss = 0
     
    for train_x, train_y in train_loader:
        train_x, train_y = Variable(train_x), Variable(train_y)
        # print(train_x) # 트레이닝 데이터셋이 총 104개 인데 배치사이즈가 16이므로
                         # 배치 당 7개의 텐서를 갖는다
        optimizer.zero_grad()
        
        output = model(train_x)
        
        loss = criterion(output, train_y)
        # print(train_x)
        loss.backward()
        print(loss)
        optimizer.step()
        # print(loss.item())
        total_loss += loss.item()
        
    if (epoch+1)%50 == 0:
        print(epoch+1, total_loss)
   
    print("------------------")

tensor(24.8538, grad_fn=<NllLossBackward>)
tensor(303940.8125, grad_fn=<NllLossBackward>)
tensor(3.0669, grad_fn=<NllLossBackward>)
tensor(79.7040, grad_fn=<NllLossBackward>)
tensor(0.6931, grad_fn=<NllLossBackward>)
tensor(0.6932, grad_fn=<NllLossBackward>)
tensor(0.6916, grad_fn=<NllLossBackward>)
------------------
tensor(0.6910, grad_fn=<NllLossBackward>)
tensor(0.6904, grad_fn=<NllLossBackward>)
tensor(0.7044, grad_fn=<NllLossBackward>)
tensor(0.6965, grad_fn=<NllLossBackward>)
tensor(0.6958, grad_fn=<NllLossBackward>)
tensor(0.6932, grad_fn=<NllLossBackward>)
tensor(0.6950, grad_fn=<NllLossBackward>)
------------------
tensor(0.7026, grad_fn=<NllLossBackward>)
tensor(0.6855, grad_fn=<NllLossBackward>)
tensor(0.6891, grad_fn=<NllLossBackward>)
tensor(0.6994, grad_fn=<NllLossBackward>)
tensor(0.6808, grad_fn=<NllLossBackward>)
tensor(0.6945, grad_fn=<NllLossBackward>)
tensor(0.6821, grad_fn=<NllLossBackward>)
------------------
tensor(0.6801, grad_fn=<NllLossBackward>)
tensor(0.686

tensor(0.6740, grad_fn=<NllLossBackward>)
tensor(0.6472, grad_fn=<NllLossBackward>)
------------------
tensor(0.7006, grad_fn=<NllLossBackward>)
tensor(0.6708, grad_fn=<NllLossBackward>)
tensor(0.7160, grad_fn=<NllLossBackward>)
tensor(0.6992, grad_fn=<NllLossBackward>)
tensor(0.6855, grad_fn=<NllLossBackward>)
tensor(0.6855, grad_fn=<NllLossBackward>)
tensor(0.6454, grad_fn=<NllLossBackward>)
------------------
tensor(0.6536, grad_fn=<NllLossBackward>)
tensor(0.6854, grad_fn=<NllLossBackward>)
tensor(0.7373, grad_fn=<NllLossBackward>)
tensor(0.6853, grad_fn=<NllLossBackward>)
tensor(0.7003, grad_fn=<NllLossBackward>)
tensor(0.7138, grad_fn=<NllLossBackward>)
tensor(0.6221, grad_fn=<NllLossBackward>)
------------------
tensor(0.6853, grad_fn=<NllLossBackward>)
tensor(0.7187, grad_fn=<NllLossBackward>)
tensor(0.6853, grad_fn=<NllLossBackward>)
tensor(0.7004, grad_fn=<NllLossBackward>)
tensor(0.6710, grad_fn=<NllLossBackward>)
tensor(0.6853, grad_fn=<NllLossBackward>)
tensor(0.6701, grad

tensor(0.7122, grad_fn=<NllLossBackward>)
tensor(0.6977, grad_fn=<NllLossBackward>)
------------------
tensor(0.6859, grad_fn=<NllLossBackward>)
tensor(0.6859, grad_fn=<NllLossBackward>)
tensor(0.6976, grad_fn=<NllLossBackward>)
tensor(0.6636, grad_fn=<NllLossBackward>)
tensor(0.7244, grad_fn=<NllLossBackward>)
tensor(0.6968, grad_fn=<NllLossBackward>)
tensor(0.6557, grad_fn=<NllLossBackward>)
------------------
tensor(0.7112, grad_fn=<NllLossBackward>)
tensor(0.6859, grad_fn=<NllLossBackward>)
tensor(0.7207, grad_fn=<NllLossBackward>)
tensor(0.6676, grad_fn=<NllLossBackward>)
tensor(0.6519, grad_fn=<NllLossBackward>)
tensor(0.6993, grad_fn=<NllLossBackward>)
tensor(0.6987, grad_fn=<NllLossBackward>)
------------------
tensor(0.6731, grad_fn=<NllLossBackward>)
tensor(0.7124, grad_fn=<NllLossBackward>)
tensor(0.7098, grad_fn=<NllLossBackward>)
tensor(0.6755, grad_fn=<NllLossBackward>)
tensor(0.6741, grad_fn=<NllLossBackward>)
tensor(0.7109, grad_fn=<NllLossBackward>)
tensor(0.6522, grad

In [10]:
test_x, test_y = Variable(test_X), Variable(test_Y)


result = torch.max(model(test_x).data, 1)[1]

print("test_y:", test_y)
print("result :", torch.max(model(test_x).data, 1)) # 두번째 인수는 해당 차원에서 맥스값
# 1보다 작은값 (소프트맥스의 리턴값) 을 log화 시키기 때문에 음수값으로 나온다
                                                    
# print(result)

accuracy = sum(test_y.data.numpy() == result.numpy())/len(test_y.data.numpy())

accuracy

test_y: tensor([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0])
result : (tensor([-0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077,
        -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077,
        -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077, -0.6077,
        -0.6077, -0.6077]), tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]))


0.5384615384615384

In [66]:

a = torch.Tensor(3, 3)
print(a)
int(2.6778e+20)


tensor([[2.2924e-37, 0.0000e+00, 1.7438e+02],
        [4.1641e+12, 7.5338e+28, 5.0511e-39],
        [1.8724e+28, 2.5353e+30, 1.3733e-43]])


267780000000000000000