In [2]:
import torch

# Transpose 개념

In [15]:
x = torch.randn(1,6)
x

tensor([[-0.1376,  0.4410, -1.1774, -1.3296, -0.0359,  0.4220]])

In [21]:
y = torch.transpose(x, 1,1)
y


tensor([[-0.1376,  0.4410, -1.1774, -1.3296, -0.0359,  0.4220]])

In [48]:
# 차원을 교환하는방식이다

x = torch.randint(1,10,(2,2,2,2))
x

tensor([[[[5, 8],
          [8, 8]],

         [[1, 8],
          [9, 6]]],


        [[[5, 2],
          [5, 4]],

         [[3, 1],
          [7, 1]]]])

In [56]:
y = torch.transpose(x, 0,3)
y

tensor([[[[5, 5],
          [8, 5]],

         [[1, 3],
          [9, 7]]],


        [[[8, 2],
          [8, 4]],

         [[8, 1],
          [6, 1]]]])